name             'demo'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures demo'
long_description 'Installs/Configures demo'
version          '0.1.0'
depends  'java', '~> 1.50.0'
depends  'jenkins', '~> 5.0.3'
depends  'maven', '~> 5.0.1'
depends 'git', '~> 6.1.0'